### ISSUE TITLE
Ch13 - Bit Vectors: memory leak

### ISSUE THREAD

**Issue by ylme** [drh/cii#12]
https://github.com/drh/cii/blob/9cb8b5f0a3b634a7459f1788b07d1d2321b8689c/src/bit.c#L16

`setop` only use one of the `sequal, snull, tnull`. But the other two variables don't get freed.

**Comment by MVEMCJSUNPE** [comment]
One would think that there would be a memory leak. However, I don't think that is the actual case here. When I invoked the C processor on bit.c (cpp bit.c > bit.i), I got something like this for Bit_union:
```
Bit_T * Bit_union(Bit_T *s, Bit_T *t) {
    if (s == t) {·
        assert(s);
        return copy(t);·
    } else if (s == NULL) {·
        assert(t);·
        return Bit_new(t->length);·
    } else if (t == NULL) {·
        return Bit_new(s->length);·
    } else {
        int i;
        Bit_T *bv;
        assert(s->length == t->length);
        bv = Bit_new(s->length);
        for (i = nwords(s->length); i-- > 0;)·
            bv->words[i] = s->words[i] | t->words[i];
        return bv;
    };
}
```
So, as we can see; "the other two variables" don't need to be freed, because only one variable is malloced depending on the branch. But don't take my words for granted. You can run the code through the C preprocessor yourself (I had to edit the mess from the C preprocessor to make it look sane for Github)
